org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=false

minecraft_version=26.2
loader_version=0.15.+
fabric_version=0.100.+

maven_group=com.outrightwings.auric_arcanum
archives_base_name=auric-arcanum
mod_version=1.1.0
mod_name=Auric Arcanum
mod_description=Synergistic Elemental Magic Mod
mod_author=OutrightWings
mod_license=MIT
